site_name: College Distance Exploration
theme:
  name: "readthedocs"
  icon:
    admonition:
      note: material/alert-circle
nav:
  - Home: index.md
  - Data Explore: data_explore.md
  - Feature Engineering: feature_engineering.md
  - Creating a model: model_training.md

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - tables
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
