# .github/workflows/ci.yml

name: CI/CD Pipeline for preparing data

# Wykonuj akcje przy każdym pushu do gałęzi main
on:
  push:
    branches:
      - main

jobs:
  checkout-and-download-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: 'PJATK-ASI-2024/Lab2---Obr-bka-danych'
          token: ${{ secrets.GPH_TOKEN }}
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            generator_danych.py
            

      - name: Setup Python and requirements
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install pandas numpy Faker
      - run: python generator_danych.py 24982
