# .github/workflows/ci.yml

name: CI/CD Pipeline for preparing data

# Wykonuj akcje przy każdym pushu do gałęzi main
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened,  assigned, synchronize ]
  pull_request_review:
    types: [ edited, dismissed ]

jobs:
  checkout-and-download-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Lab-2 repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            requirements.txt
            get_spreadsheet_values.py
      - run: ls -lha


      - name: Setup Python and requirements
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt

      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: 'PJATK-ASI-2024/Lab2---Obr-bka-danych'
          token: ${{ secrets.GPH_TOKEN }}
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            generator_danych.py

      - run: ls -lha
      - run: python generator_danych.py -s 24982
      - run: python get_spreadsheet_values.py

