# .github/workflows/ci.yml

name: CI/CD Pipeline for preparing data

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened,  assigned, synchronize ]
  pull_request_review:
    types: [ edited, dismissed ]

jobs:
  checkout-and-download-script:
    env:
      GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: 'PJATK-ASI-2024/Lab2---Obr-bka-danych'
          path: task_repo
          token: ${{ secrets.GPH_TOKEN }}

      - name: Setup Python and requirements
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r main/requirements.txt

      - name: Run Python scripts
        run: |
          python task_repo/generator_danych.py -s 24982
          ls -l
          ls task_repo/ -l
          python main/get_spreadsheet_values.py --cred "$GOOGLE_SHEETS_CREDENTIALS" --spreadsheet "$SPREADSHEET_ID" --file "../task_repo/data_student_24982.csv"

