# .github/workflows/ci.yml

name: CI/CD Pipeline for creating model

on:
  push:
    branches:
      - main
      - feat/*
  workflow_dispatch:

jobs:
  Lab-03:
    runs-on: self-hosted

    permissions:
      contents: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          pip install -r dependencies.txt
          which python
          python --version
            

      - name: Deploy to GitHub Pages
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          CONFIG_FILE: documentation/mkdocs.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.15/x64/bin/python
