# .github/workflows/ci.yml

name: CI/CD Pipeline for preparing data

# Wykonuj akcje przy każdym pushu do gałęzi main
on:
  push:
    branches:
      - main

jobs:
  checkout-and-download-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: PJATK-ASI-2024/Lab2---Obr-bka-danych
          path: main
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            generator_danych.py

#      - name: Checkout my repo
#        uses: actions/checkout@v4
#        with:
#          path: main
