# .github/workflows/ci.yml

name: CI/CD Pipeline for ML Model Training

# Wykonuj akcje przy każdym pushu do gałęzi main
on:
  push:
    branches:
      - main

jobs:
  checkout-and-download-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: PJATK-ASI-2024/Lab2---Obr-bka-danych
          sparse-checkout: |
            generator_danych.py
          sparse-checkout-cone-mode: false
          path: Lab2--Obr-bka-danych

      - name: Checkout my repo
        uses: actions/checkout@v4
        with:
          repository: PJATK-ASI-2024/Lab-2_s24982
          path: main
