# .github/workflows/ci.yml

name: CI/CD Pipeline for creating model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Lab-4:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
