# .github/workflows/ci.yml

name: CI/CD Pipeline for preparing data

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened,  assigned, synchronize ]
  pull_request_review:
    types: [ edited, dismissed ]

jobs:
  Lab-03:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
