# .github/workflows/ci.yml

name: CI/CD Pipeline for preparing data

on:
  push:
    branches:
      - Lab-2
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened,  assigned, synchronize ]
  pull_request_review:
    types: [ edited, dismissed ]


jobs:
  Lab-02:
    env:
      GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    runs-on: self-hosted

    steps:
      - name: Checkout
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: 'PJATK-ASI-2024/Lab2---Obr-bka-danych'
          path: task_repo
          token: ${{ secrets.GPH_TOKEN }}

      - name: Setup Python requirements
        run: pip install -r main/requirements.txt

      - name: Generate data and upload
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          python task_repo/generator_danych.py -s 24982
          python main/generate_upload.py --cred "$GOOGLE_SHEETS_CREDENTIALS" --spreadsheet "$SPREADSHEET_ID" --file "data_student_24982.csv"

      - name: Prepare data and upload
        if: ${{ github.event_name == 'push' }}
        run: |
          python main/get_prepare_upload.py --cred "$GOOGLE_SHEETS_CREDENTIALS" --spreadsheet "$SPREADSHEET_ID"

      - name: Show raport
        if: ${{ github.event_name == 'push' }}
        run: cat raport.txt

      - name: Show log
        if: ${{ github.event_name == 'push' }}
        run: cat log_get_prepare_upload.txt

      - name: Archive files from uploading
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          path: |
            data_student_24982.csv
            log_generate_upload.txt

      - name: Archive files from preparing data
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v4
        with:
          path: |
            prepared.csv
            raport.txt
            log_get_prepare_upload.txt

