# .github/workflows/ci.yml

name: CI/CD Pipeline for creating model

on:
  push:
    branches:
      - main
      - feat/*
  workflow_dispatch:

jobs:
  Lab-03:
    runs-on: self-hosted

    permissions:
      contents: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          pip install -r dependencies.txt
          which python
          python --version

      - name: Run python script
        run: python main.py --plots


      - name: Deploy MkDocs to GitHub Pages
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          CONFIG_FILE: documentation/mkdocs.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.15/x64/bin/python

      - name: Debug
        run: |
          cd documentation
          uname -v
          echo -e "plugins:\n  - with-pdf:\n      output_path: ../../report.pdf" >> mkdocs.yml
          cat mkdocs.yml
          mkdocs build
          ls -lha

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            logs.txt
            logging.txt
            model.pkl
